### ISSUE TITLE
Some case errors 

### ISSUE THREAD

**Issue by WizardOfWor1969** [FluBBaOfWard/NitroGrafx#1]
If you try building with a case sensitive file system, you can not build as there is a case sensitivity error in the file FileHelper.c 

line 10 should be changed to:
#include "Unzip/unzipnds.h"

There is a simliar error in the makefile , line 151 which will cause a link error. 
it should read:

source/Shared/Unzip \

I was able to work through it and build otherwise, but as there are no binary releases and anyone wanting to run this has to build it, I figured I would point this out.

**Comment by FluBBaOfWard** [comment]
Thanks a lot, can you check if my latest commit fixes the issues?

**Comment by WizardOfWor1969** [comment]
Just got latest commit, there is a case problem with the shared file, FileHelper.c, line 13 should be:
 
#include "../FileHandling.h"

**Comment by FluBBaOfWard** [comment]
Like that?

**Comment by FluBBaOfWard** [comment]
Closing since no reply after 3 months.
